---
- name: Install Git PPA
  apt_repository:
    repo: ppa:git-core/ppa
  become: yes

- name: Install Latest Git
  package:
    name: git
    state: latest
  become: yes

- name: Install Python PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: yes

- name: Install Latest Python 3.7
  package:
    name: python3.7
    state: latest
  become: yes

- name: Install Common Tools
  package:
    name:
      - htop
    state: present
  become: yes
