---
# Force Neovim rebuild even if it exists (usually used for upgrading) 
neovim_force_rebuild: False
# Which Git tag to use when pulling the latest Neovim code?
# Reference: https://github.com/neovim/neovim/tags
neovim_release_tag: stable

