---
- name: Check if Neovim is Installed
  stat:
    path: /usr/local/bin/nvim
  register: neovim_stat_result

- name: Install Neovim
  block:
    - name: Load Neovim Variables
      include_vars: "{{ item }}"
      with_first_found:
        - "os_family/{{ ansible_os_family }}.yml"
        - default.yml

    - name: Install Neovim Pre-requisites
      package:
        name: "{{ neovim_packages }}"
        state: present

    - name: Clone Neovim Repo
      git:
        repo: https://github.com/neovim/neovim
        dest: "{{ tempdir.path }}/neovim/git"
        version: "{{ neovim_release_tag }}"

    - name: Build Neovim from Source
      command: "make CMAKE_BUILD_TYPE=Release"
      args:
        chdir: "{{ tempdir.path }}/neovim/git"
      register: neovim_build_result
      failed_when: neovim_build_result.rc != 0

    - name: Install Neovim from Source
      command: "make install"
      args:
        chdir: "{{ tempdir.path }}/neovim/git"
  # Only install when we're forcing a rebuild or the nvim executable doesn't exist
  when: (neovim_force_rebuild == True) or (neovim_stat_result.stat.exists == False)